mod auto_config;
mod catalog_state;
mod config;
mod mcp;
mod memory;
mod provider;
mod update;

pub use auto_config::AutoConfigIntent;
pub use auto_config::AutoConfigResult;
pub use auto_config::apply_auto_config;
pub use auto_config::detect_auto_config;
pub use auto_config::update_installed_skill;
pub use catalog_state::ConfiguredMcp;
pub use catalog_state::InstalledSkill;
pub use catalog_state::list_configured_mcp;
pub use catalog_state::list_installed_skills;
pub use catalog_state::remove_configured_mcp;
pub use catalog_state::remove_installed_skill;
pub use catalog_state::set_mcp_enabled;
pub use catalog_state::set_skill_enabled;
pub use config::ModelChoice;
pub use config::ProviderConfig;
pub use config::ProviderDocument;
pub use config::ProviderKind;
pub use config::ProviderRegistry;
pub use config::ProviderSettings;
pub use config::RemoteCompactionMode;
pub use mcp::McpRuntime;
pub use mcp::McpServerStatus;
pub use memory::Memory;
pub use memory::MemoryManager;
pub use memory::MemoryScope;
pub use memory::MemoryType;
pub use provider::HttpModelProvider;
pub use update::UpdateCheckResult;
pub use update::check_for_update;
