[package]
name = "tiyo-services"
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
tiyo-engine = { path = "../engine" }
chrono.workspace = true
futures-util.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_yaml.workspace = true
md5.workspace = true
tokio.workspace = true

[dev-dependencies]
tempfile.workspace = true
