[package]
name = "tiyo-catalogs"
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
serde.workspace = true
serde_json.workspace = true
reqwest.workspace = true
zip.workspace = true

[dev-dependencies]
tempfile.workspace = true
